os: linux
dist: xenial
language: java

# jdk
jdk:
  - openjdk11

# verify the build
.verify: &verify
  stage: test
  script:
    - 'mvn verify'
    - 'mvn test'
  except:
    - master

# Verify merge requests using JDK8
verify:
  <<: *verify
  except:
    - master

build:
  stage: build
  script:
    - mvn clean package